#!/bin/bash

set -e

# cd to the directory containing this crate's Cargo.toml so that we don't need
# to pass --manifest-path to every `cargo` command.
cd "$(dirname "$0")"

# This is a convenience script for running a broad swath of tests across
# features. We don't test the complete space, since the complete space is quite
# large.
echo "===== DEFAULT FEATURES ====="
cargo test

features=(
    # FIXME: We currently don't test 'std' without some kind of tzdb because
    # it's pretty annoying to filter out tests that rely on lookups to succeed.
    # But we should probably just bite that bullet.
    # "std"
    "alloc"
    "alloc tzdb-bundle-always"
    "std tzdb-bundle-platform tzdb-bundle-always"
    "std tzdb-bundle-platform tzdb-bundle-always tzdb-zoneinfo"
    "std tzdb-bundle-platform tzdb-zoneinfo"
    "std tzdb-bundle-always tzdb-zoneinfo"
    "std tzdb-bundle-always logging"
    "std tzdb-bundle-always serde"
)
for f in "${features[@]}"; do
    echo "===== FEATURE: $f ====="
    cargo test --lib --no-default-features --features "$f"
    cargo test --test integration --no-default-features --features "$f"
done
