#!/usr/bin/env bash

set -eo pipefail

: "${JIFF_ALLOW_DIRTY:=}"
if [ -z "$JIFF_ALLOW_DIRTY" ]; then
  if [ -n "$(git status --porcelain)" ]; then
    echo "repository must be in a clean state"
    exit 1
  fi
fi
if ! [ -f ./crates/jiff-cli/Cargo.toml ]; then
  echo "must run in the root of a jiff repository checkout" >&2
  exit 1
fi

crate="$1"
shift
next_version="$2"
if [ -n "$next_version" ]; then
  shift
fi

release_dir="$(dirname "$0")"
case $crate in
  jiff)
    if [ -z "$next_version" ]; then
      next_version="$("$release_dir"/get-next-version ./crates/jiff/Cargo.toml)"
    fi
    "$release_dir"/update-version ./crates/jiff/Cargo.toml "$next_version"
    "$release_dir"/update-version ./crates/jiff-static/Cargo.toml "$next_version"
    sed -i 's/^\(jiff-static = { version = \)"=[0-9.]\+"/\1"='$next_version'"/g' ./crates/jiff/Cargo.toml
    git commit --quiet --all --file - <<EOF
$next_version
EOF
    ;;
  jiff-core)
    if [ -z "$next_version" ]; then
      next_version="$("$release_dir"/get-next-version ./crates/jiff-core/Cargo.toml)"
    fi
    "$release_dir"/update-version ./crates/jiff-core/Cargo.toml "$next_version"
    sed -i 's/^\(jcore = { version = \)"[0-9.]\+"/\1"'$next_version'"/g' ./Cargo.toml
    git commit --quiet --all --file - <<EOF
jiff-core-$next_version
EOF
    ;;
  jiff-tzdb)
    if [ -z "$next_version" ]; then
      next_version="$("$release_dir"/get-next-version ./crates/jiff-tzdb/Cargo.toml)"
    fi
    "$release_dir"/update-version ./crates/jiff-tzdb/Cargo.toml "$next_version"
    sed -i 's/^\(jiff-tzdb = { version = \)"[0-9.]\+"/\1"'$next_version'"/g' ./Cargo.toml
    git commit --quiet --all --file - <<EOF
jiff-tzdb-$next_version
EOF
esac
