#!/usr/bin/env bash

# Ripped out of:
# https://github.com/BurntSushi/dotfiles/blob/fb213eebcbeb9423bde476446478d32a81637212/bin/cargo-up

set -euo pipefail

function current_version {
  manifest="$1"
  rg '^version.+#:version$' "$manifest" | sed 's/.*"\([0-9]\+\.[0-9]\+\.[0-9]\+\)".*/\1/g'
}

if ! [ -f ./crates/jiff-cli/Cargo.toml ]; then
  echo "must run in the root of a jiff repository checkout" >&2
  exit 1
fi

cargo_toml="$1"
if [ -z "$cargo_toml" ]; then
  echo "Usage: $(basename "$0") <path-to-cargo-toml>" >&2
  exit 1
fi
current_version "$cargo_toml"
