[package]
name = "jiff-tzdb-platform"
version = "0.1.1"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>"]
license = "Unlicense OR MIT"
homepage = "https://github.com/BurntSushi/jiff/tree/master/jiff-tzdb-platform"
repository = "https://github.com/BurntSushi/jiff"
documentation = "https://docs.rs/jiff-tzdb-platform"
description = """
The entire Time Zone Database embedded into your binary for specific platforms.
"""
categories = ["date-and-time"]
keywords = ["date", "time", "temporal", "zone", "iana"]
workspace = ".."
edition = "2021"
rust-version = "1.70"
include = ["/*.rs", "COPYING", "LICENSE-MIT", "UNLICENSE"]

[lib]
name = "jiff_tzdb_platform"
bench = false
path = "lib.rs"

[dependencies]
jiff-tzdb = { version = "0.1.1", path = "../jiff-tzdb" }
