[package]
name = "jiff-tzdb"
version = "0.1.2"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>"]
license = "Unlicense OR MIT"
homepage = "https://github.com/BurntSushi/jiff/tree/master/jiff-tzdb"
repository = "https://github.com/BurntSushi/jiff"
documentation = "https://docs.rs/jiff-tzdb"
description = "The entire Time Zone Database embedded into your binary."
categories = ["date-and-time"]
keywords = ["date", "time", "temporal", "zone", "iana"]
workspace = "../.."
edition = "2021"
rust-version = "1.70"
include = ["/*.rs", "/*.dat", "COPYING", "LICENSE-MIT", "UNLICENSE"]

[lib]
name = "jiff_tzdb"
bench = false
path = "lib.rs"
